apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapi
  labels:
    app: yapi
spec:
  selector:
    matchLabels:
      app: yapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yapi
    spec:
      containers:
      - name: yapi
        image: zhanghaichang/yapi:1.5.0
        ports:
        - containerPort: 3000
        workingDir: /api/vendors
        args:
          - server/app.js
        volumeMounts:
          - mountPath: /api/config.json
            name: yapi-config
            subPath: config.json
      volumes:
        - name: yapi-config
          configMap:
            name: yapi-config
            items:
              - key: config.json
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: yapi
  labels:
    app: yapi
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31112
  selector:
    app: yapi
  type: NodePort
