apiVersion: v1
kind: ConfigMap
metadata:
  name: yapi-config
data:
  config.json: '{"port": "3000", "closeRegister": true, "adminAccount": "admin@topcheer.com", "db": {"servername": "mongo", "DATABASE": "yapi", "port": 27017}}'
