apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mysql-redmine.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: redmine_production
        - name: DB_PASS
          value: password
        - name: DB_USER
          value: redmine
        image: sameersbn/mysql:5.7.22-1
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-claim0
      restartPolicy: Always
      volumes:
      - name: mysql-claim0
        hostPath:
          path: /srv/docker/redmine/mysql
#        persistentVolumeClaim:
#          claimName: mysql-claim0
status: {}
