apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: kibana
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kibana
        name: kibana
        ports:
        - containerPort: 5601
