apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: tcp
  selector:
    app: elasticsearch
